[package]
name = "retrobasic"
version = "0.1.0"
authors = ["Salim Alam"]

[dependencies]
clap = "2"
log = "0.3"
rand = "0.3"
dimsum = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
env_logger = "*"
